version: '3'
services:
  mysql:
    image: mysql:5.7.39-debian
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=1000
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456